- hosts: R1
  gather_facts: no

  tasks:
    - name: Проверяем доступность по SSH
      wait_for_connection:
        delay: 5
        timeout: 60

    - name: Lab 1 - Включить VLAN 123 на портах KK (FastEthernet1/0/1, FastEthernet1/0/2)
      cisco.ios.ios_config:
        parents: "interface FastEthernet1/0/1"
        lines:
          - switchport mode access
          - switchport access vlan 123
          - no cdp enable
